### ISSUE TITLE
Please add your binary a digital signatur/ cert

### ISSUE THREAD

**Issue by beerisgood** [damienvanrobaeys/Windows_Sandbox_Editor#1]
I use Windows feature "Validate Admin Code Signatures" which check for a cryptographic signature if the file use UAC/ wan't admin right's.

Also this would reduce false positives and lower SmartScreen problems.

**Comment by ImaBadCoder** [comment]
agree with this. Seems like this project is abandoned, but love the idea and I hope that is not the case.

**Comment by damienvanrobaeys** [comment]
> agree with this. Seems like this project is abandoned, but love the idea and I hope that is not the case.

I will try to upload required files before the week-end, the project is not abandoned :-)

**Comment by ozskywalker** [comment]
Checking in.. digital signature would help immensely, especially as Windows Defender is reporting the primary EXE is malicious.

```
Detected:  Trojan:Win32/AgentTesla!ml
Status: Removed
A threat or app was removed from this device.

webfile: C:\Users\luke\Downloads\Windows Sandbox Editor.exe|https://raw.githubusercontent.com/damienvanrobaeys/Windows_Sandbox_Editor/master/EXE/Windows%20Sandbox%20Editor.exe|pid:15316,ProcessStart:132852764023776158
```
