### ISSUE TITLE
Possible issues with Windows 11

### ISSUE THREAD

**Issue by gabefair** [damienvanrobaeys/Windows_Sandbox_Editor#2]
I'm curious if anyone has gotten this to work with Windows 11. I haven't gotten it to run successfully since I upgraded to windows 11. No errors, it just never opens up.

**Comment by damienvanrobaeys** [comment]
Actually the issue reported with w11 is with powershell.
Indeed there is no context menu for ps1.
Is that yours ?

**Comment by gabefair** [comment]
You are totally right. Thank you so much for helping me. Thank you

**Comment by damienvanrobaeys** [comment]
You're welcome.
I have already reported this issue to MS.
Hoping they will resolve it soon.
