### ISSUE TITLE
Virus. False positive?

### ISSUE THREAD

**Issue by markcarsonceed** [damienvanrobaeys/Windows_Sandbox_Editor#3]
Virus found in master zip: Trojan:Win32/Mamson.A!ac, which may be a false positive?

**Comment by damienvanrobaeys** [comment]
Yep because of the EXE. Many exe generator create false positive 😫

**Comment by damienvanrobaeys** [comment]
Yep tis is false positive like in many EXE converters.
That's why i added i alternative solution to the EXE.
https://www.systanddeploy.com/2019/05/powershell-tool-windows-sandbox.html


![image](https://user-images.githubusercontent.com/8832278/156116113-bddf1171-9bfa-4ebf-b777-d897b3132fb9.png)

**Comment by ezxpro** [comment]
I really think you should clarify things a little bit. Your .exe got detected by 30 engines in VirusTotal , see : 

https://www.virustotal.com/gui/file/cde29a4fd40c984d7201f1360cf2d489343732262326a08f1b0b92b35ee2cdb1?nocache=1

That's highly unnusual for a false positive. Malwarebytes desktop is also detecting it.

BTW, you don't include ANY source code for the .EXE itself, plus you don't give any information about the false positives in the project's main page. You also don't state anything about it being a "generated .EXE" or "converted EXE", whatever that means.

If you ask me, everything about this file looks fishy and I'm inclined to believe this is actual malware
