### ISSUE TITLE
Microsoft Defender and Edge's SmartScreen both detect this as malware

### ISSUE THREAD

**Issue by ghost** [damienvanrobaeys/Windows_Sandbox_Editor#5]
![Screenshot 2022-09-07 235158](https://user-images.githubusercontent.com/72892766/188960354-bc5f8e20-4832-4a66-b2c6-38a6dcdcb527.png)

**Comment by kfrancis** [comment]
![image](https://user-images.githubusercontent.com/67574/215537216-9478f81d-7bce-4e05-b7f6-ec495c752944.png)

**Comment by rj2Skipper** [comment]
August 2023
still malware

**Comment by ghost** [comment]
Still a very harmful EXE as a Trojan Wacatac.H!ml

**Comment by damienvanrobaeys** [comment]
There is no malware, troojan in the EXE. Please read my post: https://www.systanddeploy.com/2019/05/powershell-tool-windows-sandbox.html
It's a false positive just like in a lot of EXE created with PowerShell.
